# Generated by Django 4.2.7 on 2023-11-19 17:02

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_options_alter_car_features_alter_car_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Bluetooth Handset', 'Bluetooth Handset'), ('dual airbags', 'dual airbags'), ('Touchscreen infotainment', 'Touchscreen infotainment'), ('ABS', 'ABS'), ('Panoramic sunroof', 'Panoramic sunroof'), ('rear parking sensors', 'rear parking sensors'), ('Harman infotainment', 'Harman infotainment'), ('Leather seats', 'Leather seats'), ('LED headlights', 'LED headlights'), ('Dual-zone climate control', 'Dual-zone climate control'), ('ADAS', 'ADAS'), ('connected car tech', 'connected car tech')], max_length=228, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AP', 'Andra Pradesh'), ('DL', 'Delhi'), ('TS', 'Telangana'), ('MH', 'Maharashtra'), ('KA', 'Karnataka')], max_length=100),
        ),
    ]
