# Generated by Django 4.2.7 on 2023-11-20 04:50

import django.core.validators
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_features_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Cruise Control', 'Cruise Control'), ('Audio Interface', 'Audio Interface'), ('Bluetooth Handset', 'Bluetooth Handset'), ('dual airbags', 'dual airbags'), ('Touchscreen infotainment', 'Touchscreen infotainment'), ('ABS', 'ABS'), ('Panoramic sunroof', 'Panoramic sunroof'), ('rear parking sensors', 'rear parking sensors'), ('Harman infotainment', 'Harman infotainment'), ('Leather seats', 'Leather seats'), ('LED headlights', 'LED headlights'), ('Dual-zone climate control', 'Dual-zone climate control'), ('ADAS', 'ADAS'), ('connected car tech', 'connected car tech'), ('Apple CarPlay', 'Apple CarPlay'), ('Android Auto', 'Android Auto'), ('Lane Keeping Assist', 'Lane Keeping Assist'), ('Adaptive Cruise Control', 'Adaptive Cruise Control'), ('Bluetooth Connectivity', 'Bluetooth Connectivity'), ('Steering-Mounted Controls', 'Steering-Mounted Controls'), ('Wireless phone charging', 'Wireless phone charging'), ('Dual-zone climate control', 'Dual-zone climate control'), ('SmartPlay infotainment', 'SmartPlay infotainment'), ('SYNC 3 infotainment', 'SYNC 3 infotainment'), ('Rearview camera', 'Rearview camera'), ('Sporty alloy wheels', 'Sporty alloy wheels'), ('Sporty alloy wheels', 'Sporty alloy wheels'), ('Automatic climate control', 'Automatic climate control'), ('Sport suspension', 'Sport suspension')], max_length=540, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
